# Production overrides
spring.datasource.url=jdbc:postgresql://postgres:5432/disputeflow?TimeZone=UTC
spring.datasource.username=disputeflow
spring.datasource.password=disputeflow_prod_2024
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.apache.kafka=WARN
logging.level.root=WARN
logging.level.com.disputeflow=INFO
disputeflow.threadpool.default-size=3
disputeflow.threadpool.max-size=6
disputeflow.threadpool.queue-capacity=25