# App
spring.application.name=disputeflow-backend
server.port=8080

# Database (will connect via Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/disputeflow
spring.datasource.username=disputeflow
spring.datasource.password=disputeflow123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/disputeflow?TimeZone=UTC

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=disputeflow-group
spring.kafka.consumer.auto-offset-reset=earliest

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=500MB
logging.level.org.apache.kafka=WARN

# Thread Pool Configuration
disputeflow.threadpool.default-size=5
disputeflow.threadpool.max-size=10
disputeflow.threadpool.queue-capacity=25